# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JPwiWvFSaJGg1erBkS2DQqIFShnzyOZ
"""

import pathlib

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
import scipy as sc
import statsmodels as ss
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers

print(tf.__version__)

from google.colab import drive
drive.mount('/content/drive')

dados = pd.read_csv("/content/drive/MyDrive/ColabNotebooks/train.csv")
dados2 = pd.read_csv("/content/drive/MyDrive/ColabNotebooks/test.csv")

x = dados[['year', 'transmission','mileage', 'fuelType','tax','mpg','engineSize']]
y = dados['price']

x2 = dados2[['year', 'transmission','mileage', 'fuelType','tax','mpg','engineSize']]

dataset = {'Y' : y,
           'X': x}

dataset2 = {'X': x2}

dataset = pd.DataFrame(dados)

dataset2 = pd.DataFrame(dados2)

ax = sns.boxplot(data=dataset , orient='h' , width=0.5)
ax.figure.set_size_inches(12,6)
ax.set_title('Box plot', fontsize=20)
ax.set_xlabel('Reis (R$)', fontsize=16)
ax

ax1 = sns.boxplot(data=dataset2 , orient='h' , width=0.5)
ax1.figure.set_size_inches(12,6)
ax1.set_title('Box plot', fontsize=20)
ax1.set_xlabel('Reis (R$)', fontsize=16)
ax1

ax = sns.lmplot(x='year', y='price', data=dataset)

import statsmodels.api as sm

#x.loc[dataset['fuelType'] == 'Diesel', ['fuelType']] = 0
x['fuelType'] = x['fuelType'].replace(['Diesel', 'Electric', 'Hybrid','Other','Petrol'],[0,1,2,3,4])
x['transmission'] = x['transmission'].replace(['Manual', 'Automatic', 'Semi-Auto'],[0,1,2])

Y = dataset['price']
X = sm.add_constant(x)

x2['fuelType'] = x2['fuelType'].replace(['Diesel', 'Electric', 'Hybrid','Other','Petrol'],[0,1,2,3,4])
x2['transmission'] = x2['transmission'].replace(['Manual', 'Automatic', 'Semi-Auto'],[0,1,2])

X2 = sm.add_constant(x2)

resultado_regressao = sm.OLS(Y.values , X.values).fit()

print(resultado_regressao.summary())

dataset2['price'] = resultado_regressao.predict(X2)
dataset2['car_id'] = dados2['car_id']

print(dataset2[['car_id','price']])


      car_id         price
0      16589  15905.660424
1      16590  12658.419783
2      16591   9229.712061
3      16592  19915.301927
4      16593  10230.858039
...      ...           ...
2152   18741  15923.938594
2153   18742  15996.254994
2154   18743  19161.934366
2155   18744  11539.552274
2156   18745  16477.308814

[2157 rows x 2 columns]
